name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rubocop --format simple --fail-level autocorrect

    - name: Run Brakeman
      run: bundle exec brakeman -z -o brakeman-output.html

    - name: Save Brakeman report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: brakeman-report
        path: brakeman-output.html
